### ISSUE TITLE
https://github.com/overtrue/pinyin

### ISSUE THREAD

**Issue by jingle0927** [linuxdeepin/deepin-input-method#1]
https://github.com/toolgood/ToolGood.Words
https://github.com/yingrui/mahjong
https://github.com/dongyuwei/hallelujahIM
https://github.com/crownpku/Somiao-Pinyin
https://github.com/watson-song/BigVoiceInputMethod
https://github.com/studyzy/imewlconverter

**Comment by jingle0927** [comment]
https://github.com/yingrui/mahjong
https://github.com/dongyuwei/hallelujahIM
https://github.com/crownpku/Somiao-Pinyin

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
